apiVersion: v1
kind: Service
metadata:
  name: location-service
  labels:
    app: location-api
spec:
  selector:
    app: location-api
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: location-api
  name: location-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: location-api
  template:
    metadata:
      labels:
        app: location-api
    spec:
      containers:
      - image: mengjinfeng0331/location-api:latest
        name: location-api-container
        imagePullPolicy: Always
        env:
        - name: KAFKA_URL
          valueFrom:
            configMapKeyRef:
              name: location-api-configmap
              key: KAFKA_URL
        - name: KAFKA_TOPIC
          valueFrom:
            configMapKeyRef:
              name: location-api-configmap
              key: KAFKA_TOPIC
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: location-api-configmap
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: location-api-configmap
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: location-api-configmap
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: location-api-configmap
              key: DB_PORT
      restartPolicy: Always


