apiVersion: v1
kind: Service
metadata:
  name: location_event-service
  labels:
    app: location_event-api
spec:
  selector:
    app: location_event-api
  ports:
    - protocol: TCP
      port: 5005
      targetPort: 5005
      nodePort: 30003
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: location_event-api
  name: location_event-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: location_event-api
  template:
    metadata:
      labels:
        app: location_event-api
    spec:
      containers:
      - image: mengjinfeng0331/location-event-api:latest
        name: location-event-api-container
        imagePullPolicy: Always
        env:
        - name: KAFKA_URL
          valueFrom:
            configMapKeyRef:
              name: kafka-configmap
              key: KAFKA_URL
        - name: KAFKA_TOPIC
          valueFrom:
            configMapKeyRef:
              name: kafka-configmap
              key: KAFKA_TOPIC
      restartPolicy: Always


