apiVersion: v1
kind: Service
metadata:
  labels:
    service: geoconnection-svc
  name: geoconnection-svc
spec:
  ports:
  - name: "5000"
    port: 5000
    targetPort: 5000
    nodePort: 30002
  selector:
    service: geoconnection-svc
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: geoconnection-svc
  name: geoconnection-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      service: geoconnection-svc
  template:
    metadata:
      labels:
        service: geoconnection-svc
    spec:
      containers:
      - image: mengjinfeng0331/connection-api:latest
        name: udaconnect-container
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: connection-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-connection-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: connection-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: connection-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: connection-env
              key: DB_PORT
      restartPolicy: Always