apiVersion: v1
kind: ConfigMap
data:
  DB_USERNAME: "ct_admin"
  DB_NAME: "geoconnections"
  DB_HOST: "postgres-geoconnections"
  DB_PORT: "5432"
  PERSON_API_URL: "http://person-serivce:5000/"
metadata:
  name: db-geoconnections-env