apiVersion: v1
kind: Service
metadata:
  name: person-service
  labels:
    app: person-api
spec:
  selector:
    app: person-api
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30001
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: person-api
  name: person-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: person-api
  template:
    metadata:
      labels:
        app: person-api
    spec:
      containers:
      - image: mengjinfeng0331/person-api:latest
        name: person-api-container
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-person
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-person-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-person
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-person
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-person
              key: DB_PORT
      restartPolicy: Always


